
services:

  frontend:
    build:
      context: .
      dockerfile: frontent/lexiflow/Dockerfile
    ports:
      - "4555:4555"
    volumes:
      - ./frontent/lexiflow:/app
    restart: unless-stopped