services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
        - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
    ports:
      - "4555:80"
    restart: unless-stopped
    depends_on:
      - backend-node

  backend-node:
    image: ghcr.io/amer-adam/lexiflow:latest
    build:
      context: ./backend-node
    ports:
      - "4556:4556"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - backend-fastapi

  backend-fastapi:
    build:
      context: ./backend-fastapi
    ports:
      - "4557:4557"
    environment:
      - TRANSLATION_API_URL=http://libretranslate:5000/translate
      - FRONTEND_URL=${FRONTEND_URL}
      - OMP_NUM_THREADS=12
      - MKL_NUM_THREADS=12
    restart: unless-stopped
    depends_on:
      - libretranslate



  libretranslate:
    image: libretranslate/libretranslate
    ports:
      - "5000:5000"
    environment:
      - LT_LOAD_ONLY=en,zh
      - LT_DISABLE_WEB_UI=true
      - LT_DISABLE_FILES_TRANSLATION=true
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
